version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    ports:
      - "9090:9090"
    environment:
      - AR_URL=${AR_URL}
    restart: unless-stopped