version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./volumes/logs:/app/logs