name: main build and publish workflow

on: push

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: mcp

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
        retention-days: 30

  publish-to-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    environment:
      name: pypi
      url: https://pypi.org/p/maxai-mcp
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-ecr:
    name: Publish to ECR
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_AD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_AD_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          TAG_VERSION="${GITHUB_REF##*/}"
          docker build -t $REGISTRY/$ECR_REPOSITORY:$TAG_VERSION -t $REGISTRY/$ECR_REPOSITORY:latest .
          docker push $REGISTRY/$ECR_REPOSITORY:$TAG_VERSION
          docker push $REGISTRY/$ECR_REPOSITORY:latest

  build-dxt:
    name: Build DXT extension
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - extract-version
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install DXT toolchain
      run: npm install -g @anthropic-ai/dxt

    - name: Pack extension
      run: dxt pack

    - name: Upload DXT artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dxt-dist
        path: '*.dxt'

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build-dxt
    steps:
      - name: Download DXT artifacts
        uses: actions/download-artifact@v4
        with:
          name: dxt-dist
          path: ./

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.dxt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}